/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ClearFarewellInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addMessage"
      | "claim"
      | "getMessageMeta"
      | "getMyAddress"
      | "markDeceased"
      | "messageCount"
      | "ping"
      | "register"
      | "registerDefault"
      | "users",
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Deceased" | "MessageAdded" | "MessageClaimed" | "Ping" | "UserRegistered",
  ): EventFragment;

  encodeFunctionData(functionFragment: "addMessage", values: [string, BytesLike]): string;
  encodeFunctionData(functionFragment: "claim", values: [AddressLike, BigNumberish]): string;
  encodeFunctionData(functionFragment: "getMessageMeta", values: [AddressLike, BigNumberish]): string;
  encodeFunctionData(functionFragment: "getMyAddress", values?: undefined): string;
  encodeFunctionData(functionFragment: "markDeceased", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "messageCount", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "ping", values?: undefined): string;
  encodeFunctionData(functionFragment: "register", values: [BigNumberish, BigNumberish]): string;
  encodeFunctionData(functionFragment: "registerDefault", values?: undefined): string;
  encodeFunctionData(functionFragment: "users", values: [AddressLike]): string;

  decodeFunctionResult(functionFragment: "addMessage", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMessageMeta", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMyAddress", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "markDeceased", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "messageCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ping", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registerDefault", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "users", data: BytesLike): Result;
}

export namespace DeceasedEvent {
  export type InputTuple = [user: AddressLike, when: BigNumberish];
  export type OutputTuple = [user: string, when: bigint];
  export interface OutputObject {
    user: string;
    when: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessageAddedEvent {
  export type InputTuple = [
    user: AddressLike,
    index: BigNumberish,
    recipientEmailHash: BytesLike,
    recipientEmail: string,
  ];
  export type OutputTuple = [user: string, index: bigint, recipientEmailHash: string, recipientEmail: string];
  export interface OutputObject {
    user: string;
    index: bigint;
    recipientEmailHash: string;
    recipientEmail: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessageClaimedEvent {
  export type InputTuple = [
    user: AddressLike,
    index: BigNumberish,
    recipientEmailHash: BytesLike,
    recipientEmail: string,
    data: BytesLike,
  ];
  export type OutputTuple = [
    user: string,
    index: bigint,
    recipientEmailHash: string,
    recipientEmail: string,
    data: string,
  ];
  export interface OutputObject {
    user: string;
    index: bigint;
    recipientEmailHash: string;
    recipientEmail: string;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PingEvent {
  export type InputTuple = [user: AddressLike, when: BigNumberish];
  export type OutputTuple = [user: string, when: bigint];
  export interface OutputObject {
    user: string;
    when: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRegisteredEvent {
  export type InputTuple = [user: AddressLike, checkInPeriod: BigNumberish, gracePeriod: BigNumberish];
  export type OutputTuple = [user: string, checkInPeriod: bigint, gracePeriod: bigint];
  export interface OutputObject {
    user: string;
    checkInPeriod: bigint;
    gracePeriod: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ClearFarewell extends BaseContract {
  connect(runner?: ContractRunner | null): ClearFarewell;
  waitForDeployment(): Promise<this>;

  interface: ClearFarewellInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(event: TCEvent): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  addMessage: TypedContractMethod<[recipientEmail: string, data: BytesLike], [bigint], "nonpayable">;

  claim: TypedContractMethod<[user: AddressLike, index: BigNumberish], [void], "nonpayable">;

  getMessageMeta: TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [
      [string, string, boolean] & {
        recipientEmail: string;
        recipientEmailHash: string;
        delivered: boolean;
      },
    ],
    "view"
  >;

  getMyAddress: TypedContractMethod<[], [string], "view">;

  markDeceased: TypedContractMethod<[user: AddressLike], [void], "nonpayable">;

  messageCount: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  ping: TypedContractMethod<[], [void], "nonpayable">;

  register: TypedContractMethod<[checkInPeriod: BigNumberish, gracePeriod: BigNumberish], [void], "nonpayable">;

  registerDefault: TypedContractMethod<[], [void], "nonpayable">;

  users: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, boolean] & {
        checkInPeriod: bigint;
        gracePeriod: bigint;
        lastCheckIn: bigint;
        deceased: boolean;
      },
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(
    nameOrSignature: "addMessage",
  ): TypedContractMethod<[recipientEmail: string, data: BytesLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "claim",
  ): TypedContractMethod<[user: AddressLike, index: BigNumberish], [void], "nonpayable">;
  getFunction(nameOrSignature: "getMessageMeta"): TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [
      [string, string, boolean] & {
        recipientEmail: string;
        recipientEmailHash: string;
        delivered: boolean;
      },
    ],
    "view"
  >;
  getFunction(nameOrSignature: "getMyAddress"): TypedContractMethod<[], [string], "view">;
  getFunction(nameOrSignature: "markDeceased"): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;
  getFunction(nameOrSignature: "messageCount"): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(nameOrSignature: "ping"): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "register",
  ): TypedContractMethod<[checkInPeriod: BigNumberish, gracePeriod: BigNumberish], [void], "nonpayable">;
  getFunction(nameOrSignature: "registerDefault"): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(nameOrSignature: "users"): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, boolean] & {
        checkInPeriod: bigint;
        gracePeriod: bigint;
        lastCheckIn: bigint;
        deceased: boolean;
      },
    ],
    "view"
  >;

  getEvent(
    key: "Deceased",
  ): TypedContractEvent<DeceasedEvent.InputTuple, DeceasedEvent.OutputTuple, DeceasedEvent.OutputObject>;
  getEvent(
    key: "MessageAdded",
  ): TypedContractEvent<MessageAddedEvent.InputTuple, MessageAddedEvent.OutputTuple, MessageAddedEvent.OutputObject>;
  getEvent(
    key: "MessageClaimed",
  ): TypedContractEvent<
    MessageClaimedEvent.InputTuple,
    MessageClaimedEvent.OutputTuple,
    MessageClaimedEvent.OutputObject
  >;
  getEvent(key: "Ping"): TypedContractEvent<PingEvent.InputTuple, PingEvent.OutputTuple, PingEvent.OutputObject>;
  getEvent(
    key: "UserRegistered",
  ): TypedContractEvent<
    UserRegisteredEvent.InputTuple,
    UserRegisteredEvent.OutputTuple,
    UserRegisteredEvent.OutputObject
  >;

  filters: {
    "Deceased(address,uint64)": TypedContractEvent<
      DeceasedEvent.InputTuple,
      DeceasedEvent.OutputTuple,
      DeceasedEvent.OutputObject
    >;
    Deceased: TypedContractEvent<DeceasedEvent.InputTuple, DeceasedEvent.OutputTuple, DeceasedEvent.OutputObject>;

    "MessageAdded(address,uint256,bytes32,string)": TypedContractEvent<
      MessageAddedEvent.InputTuple,
      MessageAddedEvent.OutputTuple,
      MessageAddedEvent.OutputObject
    >;
    MessageAdded: TypedContractEvent<
      MessageAddedEvent.InputTuple,
      MessageAddedEvent.OutputTuple,
      MessageAddedEvent.OutputObject
    >;

    "MessageClaimed(address,uint256,bytes32,string,bytes)": TypedContractEvent<
      MessageClaimedEvent.InputTuple,
      MessageClaimedEvent.OutputTuple,
      MessageClaimedEvent.OutputObject
    >;
    MessageClaimed: TypedContractEvent<
      MessageClaimedEvent.InputTuple,
      MessageClaimedEvent.OutputTuple,
      MessageClaimedEvent.OutputObject
    >;

    "Ping(address,uint64)": TypedContractEvent<PingEvent.InputTuple, PingEvent.OutputTuple, PingEvent.OutputObject>;
    Ping: TypedContractEvent<PingEvent.InputTuple, PingEvent.OutputTuple, PingEvent.OutputObject>;

    "UserRegistered(address,uint64,uint64)": TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
    UserRegistered: TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
  };
}
