/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  SepoliaConfigUpgradeable,
  SepoliaConfigUpgradeableInterface,
} from "../../../contracts/fhevm/SepoliaConfigUpgradeable";

const _abi = [
  {
    inputs: [],
    name: "InvalidInitialization",
    type: "error",
  },
  {
    inputs: [],
    name: "NotInitializing",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint64",
        name: "version",
        type: "uint64",
      },
    ],
    name: "Initialized",
    type: "event",
  },
] as const;

export class SepoliaConfigUpgradeable__factory {
  static readonly abi = _abi;
  static createInterface(): SepoliaConfigUpgradeableInterface {
    return new Interface(_abi) as SepoliaConfigUpgradeableInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SepoliaConfigUpgradeable {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as SepoliaConfigUpgradeable;
  }
}
